const imageUrls = {
  instagram: "/images/instagram.svg",
  twitter: "/images/twitter.svg",
  linkedin: "/images/linkedin.svg",
  discord: "/images/discord.svg",
  frontend: "/images/Frontend.svg",
  backend: "/images/Backend.svg",
  mobile: "/images/MobileDevelopment.svg",
  deployment: "/images/Deployment.svg",
  qa: "/images/QA.svg",
  ux: "/images/UX.svg",
  companyLogo: "/images/Logo/CompanyLogo.svg",
  laptop: "/images/Laptop.png",
  founder: "/images/founder1.svg",
  vision: "/images/ourvision.svg",
  founder1 : "/images/Founders/founder__1.svg",
  founder2 : "/images/Founders/Founder2.svg",
  laptop4x : "/images/laptop__4x.png",
  companyLogoWithTitle : "/images/Logo/logowithTitle.svg",
  culturalDiversity : "/images/aboutUs/Culture/CulturalDiversity.svg",
  funFriday :  "/images/aboutUs/Culture/FunFriday.svg",
  learnAndGrow :  "/images/aboutUs/Culture/Learn&Grow.svg",
  passionAndRespect :  "/images/aboutUs/Culture/Passion&Respect.svg",
};

export default imageUrls;
